### ISSUE TITLE
Traditional Style of passing 'this' to callbacks no longer works

### ISSUE THREAD

**Issue by STRML** [xavi-/two-step#1]
Hey Xavi - thanks for putting this together.

What I'm wondering is: why kill the original way of using Step?

The following line:

```
User.findById(id, this);
```

Must now be changed to

```
User.findById(id, this.val());
```

Not the biggest deal in the world, but this means a less than seamless transition from Step.

**Comment by xavi-** [comment]
For readability and consistency reasons mainly.  In my experience, the `this` pointer in a javascript method is almost always an object.  I felt making it into a function/object hybrid would lead to unneeded confusion.

That said, I do agree, that making `this` into a function does align with the original Step usage as well as lead to more concise code.  I'm open to the idea of making `User.findById(id, this)` work.  The only thing holding me back is the actual implementation.  Currently `this` is simply an instance of a [`StepObj`](https://github.com/xavi-/two-step/blob/master/index.js#L45).  To make it a function/object hybrid is a little tricky.  The best solution I can think of is to change the `StepObj` constructor to this:

``` javascript
function StepObj(params, jumpTo, name) {
    var step = function() { return step.val.apply(step, arguments); };
    step._params = params;
    step._jumpTo = jumpTo;
    step._name = name; // step.name collides with Function.prototype.name

    step.__proto__ = StepObj.prototype;

    return step;
}
```

Explicitly setting `step.__proto__` gives me pause.  Can you think of a better solution?

Thanks for the feedback.

**Comment by xavi-** [comment]
Just created a branch to flesh out some of these ideas: https://github.com/xavi-/two-step/tree/this-as-callback

While doing a rough implementation, I realized that `User.findById(id, this)` is inherently ambiguous when there are multiple calls.  For example:

``` javascript
function rtnA(cb){ setTimeout(function(){ cb(null, "a"); }, 2000 * Math.random()); }
function rtnB(cb){ setTimeout(function(){ cb(null, "b"); }, 2000 * Math.random()); }

TwoStep(
    function() {
        rtnA(this);
        rtnB(this);
    },
    function(err, val1, val2) {
        // What does val1 or val2 equal to?
    }
);
```

The best we can do is make `this()` work correctly.

Also, `this.valArray()` had to change a bit.  I strongly feel that API of the object returned from `this.valArray()` should mirror `this` (aka the original StepObj) as much as possible.
