### ISSUE TITLE
removing exception handler

### ISSUE THREAD

**Issue by blmarket** [xavi-/two-step#2]
using two-step with mocha, it catches exception which should be handled by mocha.

removing exception-handling part it solves...

**Comment by xavi-** [comment]
I haven't had much experience in mocha, so I'm not 100% sure what you mean.  But, while looking into the issue, I noticed that TwoStep swallows error if they occur in the last step.  Example:

```
TwoStep(
    function() { },
    function() { throw "Swallowed"; }
);
```

I fixed this issue in the lastest push (e418fd228b64465ff53f73f8763867217138e78a).  In general TwoStep (as well as the original Step) auto catches error and passes them as the first paramater of the next step function.  This pattern seems to jive well with many of the node.js api's.

Thanks for the feed back.
