### ISSUE TITLE
listen on event-emitter

### ISSUE THREAD

**Issue by gitfy** [xavi-/two-step#3]
Hi,
Is there a possibility to listen and process a step as and when the data comes from a stream. If the listener is only able to collect all the data, and at the end it has to process, then it loses the benefit of stream. My idea is to process records as they are read in the stream keeping the memory foot print low.
Is this possible some how ?

Thanks.

**Comment by xavi-** [comment]
You're right. Many of the benefits of streams are lost when using `this.listen`.  The `this.listen` method exist strictly for convenience.  There are times when you do need the entire contents of a stream.  In those cases writing the following code gets a bit tedious:

``` javascript
TwoStep(
    function() { /* ... */ },
    function(err, emitter) {
        var chunks = [], next = this.val();
        emitter.on('data', function (chunk) { chunks.push(chunk); });
        emitter.on('error', function(err) { next(err); });
        emitter.on('end', function() { next(null, chunks) });       
    },
    function(err, chunks) { /* ... */ }
);
```

That said, if you can think of an API that make streams easier to work with while still preserving most of their benefits, I'm all ears.
